require 'spec_helper'
require 'ruby-debug'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SemestersController do

  before(:each) do
    @registration_deadline = FactoryGirl.create(:deadline)
  end

  def valid_attributes
    { 
      "name" => Semester::FALL,
      "status" => Semester::PUBLIC,
      "year" => 2001,
      "registration_deadline_id" => 1 ,
    }
  end
  
  def valid_attributes_post
    { 
      "name" => Semester::FALL,
      "status" => Semester::PUBLIC,
      "year" => 2001,
      "registration_deadline_id" => @registration_deadline.id,
    }
  end

  def semester_attributes
    {
      "name"=>"Fall", 
      "year"=>"2012", 
      "start_date(1i)"=>"2012", 
      "start_date(2i)"=>"8", 
      "start_date(3i)"=>"22", 
      "end_date(1i)"=>"2012", 
      "end_date(2i)"=>"12", 
      "end_date(3i)"=>"14", 
      "status"=>"Public", 
    }
  end
  def registration_deadline_attributes
    {
      "title"=>"Last day to submit your field placement preferences", 
      "summary"=>"Be sure to submit your field placement preferences before the deadline", 
      "due_date(1i)"=>"2012", 
      "due_date(2i)"=>"1", 
      "due_date(3i)"=>"16", 
      "due_date(4i)"=>"08", 
      "due_date(5i)"=>"00"
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SemestersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all semesters as @semesters" do
      semester = Semester.create!(valid_attributes)
      get :index, {}, valid_session
      assigns(:semesters).should eq([semester])
    end
  end

  describe "GET show" do
    it "assigns the requested semester as @semester" do
      semester = Semester.create!(valid_attributes)
      get :show, {:id => semester.to_param}, valid_session
      assigns(:semester).should eq(semester)
    end
  end

  describe "GET new" do
    it "assigns a new semester as @semester" do
      get :new, {}, valid_session
      assigns(:semester).should be_a_new(Semester)
    end
  end

  describe "GET edit" do
    it "assigns the requested semester as @semester" do
      semester = Semester.create!(valid_attributes)
      get :edit, {:id => semester.to_param}, valid_session
      assigns(:semester).should eq(semester)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Semester" do
        expect {
          post :create, {:semester => valid_attributes_post}, valid_session
        }.to change(Semester, :count).by(1)
      end

      it "assigns a newly created semester as @semester" do
        post :create, {:semester => valid_attributes_post}, valid_session
        assigns(:semester).should be_a(Semester)
        assigns(:semester).should be_persisted
      end

      it "redirects to the created semester" do
        post :create, {:semester => valid_attributes_post}, valid_session
        response.should redirect_to(Semester.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved semester as @semester" do
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        post :create, {:semester => { "name" => "invalid value" }}, valid_session
        assigns(:semester).should be_a_new(Semester)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        post :create, {:semester => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested semester" do
        semester = Semester.create!(valid_attributes)
        # Assuming there are no other semesters in the database, this
        # specifies that the Semester created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Semester.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => semester.to_param, :semester => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested semester as @semester" do
        semester = Semester.create!(valid_attributes)
        put :update, {
          :id => semester.to_param, 
          :semester => semester_attributes,
          :registration_deadline => registration_deadline_attributes
        }, valid_session
        assigns(:semester).should eq(semester)
      end

      it "redirects to the semester" do
        semester = Semester.create!(valid_attributes)
        put :update, {
          :id => semester.to_param, 
          :semester => semester_attributes,
          :registration_deadline => registration_deadline_attributes
        }, valid_session
        response.should redirect_to(semester)

      end
    end

    describe "with invalid params" do
      it "assigns the semester as @semester" do
        semester = Semester.create!(valid_attributes)
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        put :update, {:id => semester.to_param, :semester => { "name" => "invalid value" }}, valid_session
        assigns(:semester).should eq(semester)
      end

      it "re-renders the 'edit' template" do
        semester = Semester.create!(valid_attributes)
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        put :update, {:id => semester.to_param, :semester => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested semester" do
      semester = Semester.create!(valid_attributes)
      expect {
        delete :destroy, {:id => semester.to_param}, valid_session
      }.to change(Semester, :count).by(-1)
    end

    it "redirects to the semesters list" do
      semester = Semester.create!(valid_attributes)
      delete :destroy, {:id => semester.to_param}, valid_session
      response.should redirect_to(semesters_url)
    end
  end

end
